INSTALL_TARGET_PROCESSES = SpringBoard

TWEAK_NAME = Sushi
Sushi_FILES = $(wildcard *.x) $(wildcard *.m)
Sushi_PRIVATE_FRAMEWORKS = MediaRemote
Sushi_CFLAGS = -fobjc-arc -I../headers

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
