name: Build

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up dependencies
        id: setup
        run: |
          brew install ldid make
          echo "THEOS=${GITHUB_WORKSPACE}/theos" >> "${GITHUB_ENV}"
          echo "PATH=/usr/local/opt/make/libexec/gnubin:${PATH}" >> "${GITHUB_ENV}"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Install Theos
        uses: actions/checkout@v2
        with:
          repository: theos/theos
          path: theos
          submodules: recursive
      - name: Download SDK
        uses: actions/checkout@v4
        with:
          repository: theos/sdks
          path: theos/sdks
          sparse-checkout: iPhoneOS16.5.sdk
      - name: Build artifacts
        run: |
          export DEVELOPER_DIR=/Applications/Xcode_14.3.1.app/Contents/Developer
          export PACKAGE_BUILDNAME=${{ steps.setup.outputs.sha_short }}
          make clean package FINALPACKAGE=1
          make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Sushi_${{ steps.setup.outputs.sha_short }}.zip
          path: packages/*.deb
          if-no-files-found: error
      - name: Build release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          rm -rf packages
          export DEVELOPER_DIR=/Applications/Xcode_14.3.1.app/Contents/Developer
          export PACKAGE_BUILDNAME=
          make clean package FINALPACKAGE=1
          make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          body: ''
          draft: true
          files: packages/*.deb
